/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiRuntimeRouteImport } from './routes/api.runtime'
import { Route as ApiRunsRouteImport } from './routes/api.runs'
import { Route as ApiProjectRouteImport } from './routes/api.project'
import { Route as AppWorkflowsIndexRouteImport } from './routes/_app/workflows/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppAgentIndexRouteImport } from './routes/_app/agent/index'
import { Route as ApiRunsRunIdRouteImport } from './routes/api/runs/$runId'
import { Route as AppWorkflowsWorkflowIdIndexRouteImport } from './routes/_app/workflows/$workflowId/index'
import { Route as AppAgentAgentIdIndexRouteImport } from './routes/_app/agent/$agentId/index'
import { Route as ApiRunsRunIdEventsRouteImport } from './routes/api/runs/$runId/events'
import { Route as ApiAgentRunsMemoryScopeEventsRouteImport } from './routes/api/agent-runs/$memoryScope/events'
import { Route as AppWorkflowsWorkflowIdRRunIdRouteImport } from './routes/_app/workflows/$workflowId/r/$runId'
import { Route as AppAgentAgentIdRRunIdRouteImport } from './routes/_app/agent/$agentId/r/$runId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiRuntimeRoute = ApiRuntimeRouteImport.update({
  id: '/api/runtime',
  path: '/api/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRoute = ApiRunsRouteImport.update({
  id: '/api/runs',
  path: '/api/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectRoute = ApiProjectRouteImport.update({
  id: '/api/project',
  path: '/api/project',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentIndexRoute = AppAgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => AppRoute,
} as any)
const ApiRunsRunIdRoute = ApiRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => ApiRunsRoute,
} as any)
const AppWorkflowsWorkflowIdIndexRoute =
  AppWorkflowsWorkflowIdIndexRouteImport.update({
    id: '/workflows/$workflowId/',
    path: '/workflows/$workflowId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAgentAgentIdIndexRoute = AppAgentAgentIdIndexRouteImport.update({
  id: '/agent/$agentId/',
  path: '/agent/$agentId/',
  getParentRoute: () => AppRoute,
} as any)
const ApiRunsRunIdEventsRoute = ApiRunsRunIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiRunsRunIdRoute,
} as any)
const ApiAgentRunsMemoryScopeEventsRoute =
  ApiAgentRunsMemoryScopeEventsRouteImport.update({
    id: '/api/agent-runs/$memoryScope/events',
    path: '/api/agent-runs/$memoryScope/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkflowsWorkflowIdRRunIdRoute =
  AppWorkflowsWorkflowIdRRunIdRouteImport.update({
    id: '/workflows/$workflowId/r/$runId',
    path: '/workflows/$workflowId/r/$runId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAgentAgentIdRRunIdRoute = AppAgentAgentIdRRunIdRouteImport.update({
  id: '/agent/$agentId/r/$runId',
  path: '/agent/$agentId/r/$runId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/api/project': typeof ApiProjectRoute
  '/api/runs': typeof ApiRunsRouteWithChildren
  '/api/runtime': typeof ApiRuntimeRoute
  '/api/runs/$runId': typeof ApiRunsRunIdRouteWithChildren
  '/agent/': typeof AppAgentIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/workflows/': typeof AppWorkflowsIndexRoute
  '/api/agent-runs/$memoryScope/events': typeof ApiAgentRunsMemoryScopeEventsRoute
  '/api/runs/$runId/events': typeof ApiRunsRunIdEventsRoute
  '/agent/$agentId/': typeof AppAgentAgentIdIndexRoute
  '/workflows/$workflowId/': typeof AppWorkflowsWorkflowIdIndexRoute
  '/agent/$agentId/r/$runId': typeof AppAgentAgentIdRRunIdRoute
  '/workflows/$workflowId/r/$runId': typeof AppWorkflowsWorkflowIdRRunIdRoute
}
export interface FileRoutesByTo {
  '/api/project': typeof ApiProjectRoute
  '/api/runs': typeof ApiRunsRouteWithChildren
  '/api/runtime': typeof ApiRuntimeRoute
  '/': typeof AppIndexRoute
  '/api/runs/$runId': typeof ApiRunsRunIdRouteWithChildren
  '/agent': typeof AppAgentIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/workflows': typeof AppWorkflowsIndexRoute
  '/api/agent-runs/$memoryScope/events': typeof ApiAgentRunsMemoryScopeEventsRoute
  '/api/runs/$runId/events': typeof ApiRunsRunIdEventsRoute
  '/agent/$agentId': typeof AppAgentAgentIdIndexRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdIndexRoute
  '/agent/$agentId/r/$runId': typeof AppAgentAgentIdRRunIdRoute
  '/workflows/$workflowId/r/$runId': typeof AppWorkflowsWorkflowIdRRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/api/project': typeof ApiProjectRoute
  '/api/runs': typeof ApiRunsRouteWithChildren
  '/api/runtime': typeof ApiRuntimeRoute
  '/_app/': typeof AppIndexRoute
  '/api/runs/$runId': typeof ApiRunsRunIdRouteWithChildren
  '/_app/agent/': typeof AppAgentIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/workflows/': typeof AppWorkflowsIndexRoute
  '/api/agent-runs/$memoryScope/events': typeof ApiAgentRunsMemoryScopeEventsRoute
  '/api/runs/$runId/events': typeof ApiRunsRunIdEventsRoute
  '/_app/agent/$agentId/': typeof AppAgentAgentIdIndexRoute
  '/_app/workflows/$workflowId/': typeof AppWorkflowsWorkflowIdIndexRoute
  '/_app/agent/$agentId/r/$runId': typeof AppAgentAgentIdRRunIdRoute
  '/_app/workflows/$workflowId/r/$runId': typeof AppWorkflowsWorkflowIdRRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/project'
    | '/api/runs'
    | '/api/runtime'
    | '/api/runs/$runId'
    | '/agent/'
    | '/settings/'
    | '/workflows/'
    | '/api/agent-runs/$memoryScope/events'
    | '/api/runs/$runId/events'
    | '/agent/$agentId/'
    | '/workflows/$workflowId/'
    | '/agent/$agentId/r/$runId'
    | '/workflows/$workflowId/r/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/project'
    | '/api/runs'
    | '/api/runtime'
    | '/'
    | '/api/runs/$runId'
    | '/agent'
    | '/settings'
    | '/workflows'
    | '/api/agent-runs/$memoryScope/events'
    | '/api/runs/$runId/events'
    | '/agent/$agentId'
    | '/workflows/$workflowId'
    | '/agent/$agentId/r/$runId'
    | '/workflows/$workflowId/r/$runId'
  id:
    | '__root__'
    | '/_app'
    | '/api/project'
    | '/api/runs'
    | '/api/runtime'
    | '/_app/'
    | '/api/runs/$runId'
    | '/_app/agent/'
    | '/_app/settings/'
    | '/_app/workflows/'
    | '/api/agent-runs/$memoryScope/events'
    | '/api/runs/$runId/events'
    | '/_app/agent/$agentId/'
    | '/_app/workflows/$workflowId/'
    | '/_app/agent/$agentId/r/$runId'
    | '/_app/workflows/$workflowId/r/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiProjectRoute: typeof ApiProjectRoute
  ApiRunsRoute: typeof ApiRunsRouteWithChildren
  ApiRuntimeRoute: typeof ApiRuntimeRoute
  ApiAgentRunsMemoryScopeEventsRoute: typeof ApiAgentRunsMemoryScopeEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/runtime': {
      id: '/api/runtime'
      path: '/api/runtime'
      fullPath: '/api/runtime'
      preLoaderRoute: typeof ApiRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs': {
      id: '/api/runs'
      path: '/api/runs'
      fullPath: '/api/runs'
      preLoaderRoute: typeof ApiRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project': {
      id: '/api/project'
      path: '/api/project'
      fullPath: '/api/project'
      preLoaderRoute: typeof ApiProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows/': {
      id: '/_app/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent/': {
      id: '/_app/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AppAgentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/runs/$runId': {
      id: '/api/runs/$runId'
      path: '/$runId'
      fullPath: '/api/runs/$runId'
      preLoaderRoute: typeof ApiRunsRunIdRouteImport
      parentRoute: typeof ApiRunsRoute
    }
    '/_app/workflows/$workflowId/': {
      id: '/_app/workflows/$workflowId/'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId/'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent/$agentId/': {
      id: '/_app/agent/$agentId/'
      path: '/agent/$agentId'
      fullPath: '/agent/$agentId/'
      preLoaderRoute: typeof AppAgentAgentIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/runs/$runId/events': {
      id: '/api/runs/$runId/events'
      path: '/events'
      fullPath: '/api/runs/$runId/events'
      preLoaderRoute: typeof ApiRunsRunIdEventsRouteImport
      parentRoute: typeof ApiRunsRunIdRoute
    }
    '/api/agent-runs/$memoryScope/events': {
      id: '/api/agent-runs/$memoryScope/events'
      path: '/api/agent-runs/$memoryScope/events'
      fullPath: '/api/agent-runs/$memoryScope/events'
      preLoaderRoute: typeof ApiAgentRunsMemoryScopeEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows/$workflowId/r/$runId': {
      id: '/_app/workflows/$workflowId/r/$runId'
      path: '/workflows/$workflowId/r/$runId'
      fullPath: '/workflows/$workflowId/r/$runId'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdRRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent/$agentId/r/$runId': {
      id: '/_app/agent/$agentId/r/$runId'
      path: '/agent/$agentId/r/$runId'
      fullPath: '/agent/$agentId/r/$runId'
      preLoaderRoute: typeof AppAgentAgentIdRRunIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAgentIndexRoute: typeof AppAgentIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
  AppAgentAgentIdIndexRoute: typeof AppAgentAgentIdIndexRoute
  AppWorkflowsWorkflowIdIndexRoute: typeof AppWorkflowsWorkflowIdIndexRoute
  AppAgentAgentIdRRunIdRoute: typeof AppAgentAgentIdRRunIdRoute
  AppWorkflowsWorkflowIdRRunIdRoute: typeof AppWorkflowsWorkflowIdRRunIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAgentIndexRoute: AppAgentIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
  AppAgentAgentIdIndexRoute: AppAgentAgentIdIndexRoute,
  AppWorkflowsWorkflowIdIndexRoute: AppWorkflowsWorkflowIdIndexRoute,
  AppAgentAgentIdRRunIdRoute: AppAgentAgentIdRRunIdRoute,
  AppWorkflowsWorkflowIdRRunIdRoute: AppWorkflowsWorkflowIdRRunIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiRunsRunIdRouteChildren {
  ApiRunsRunIdEventsRoute: typeof ApiRunsRunIdEventsRoute
}

const ApiRunsRunIdRouteChildren: ApiRunsRunIdRouteChildren = {
  ApiRunsRunIdEventsRoute: ApiRunsRunIdEventsRoute,
}

const ApiRunsRunIdRouteWithChildren = ApiRunsRunIdRoute._addFileChildren(
  ApiRunsRunIdRouteChildren,
)

interface ApiRunsRouteChildren {
  ApiRunsRunIdRoute: typeof ApiRunsRunIdRouteWithChildren
}

const ApiRunsRouteChildren: ApiRunsRouteChildren = {
  ApiRunsRunIdRoute: ApiRunsRunIdRouteWithChildren,
}

const ApiRunsRouteWithChildren =
  ApiRunsRoute._addFileChildren(ApiRunsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiProjectRoute: ApiProjectRoute,
  ApiRunsRoute: ApiRunsRouteWithChildren,
  ApiRuntimeRoute: ApiRuntimeRoute,
  ApiAgentRunsMemoryScopeEventsRoute: ApiAgentRunsMemoryScopeEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
