/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiRuntimeRouteImport } from './routes/api.runtime'
import { Route as ApiProjectRouteImport } from './routes/api.project'
import { Route as AppWorkflowsIndexRouteImport } from './routes/_app/workflows/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppAgentIndexRouteImport } from './routes/_app/agent/index'
import { Route as AppWorkflowsWorkflowIdRunRunIdRouteImport } from './routes/_app/workflows/$workflowId/run/$runId'
import { Route as AppAgentAgentIdRunRunIdRouteImport } from './routes/_app/agent/$agentId/run/$runId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiRuntimeRoute = ApiRuntimeRouteImport.update({
  id: '/api/runtime',
  path: '/api/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectRoute = ApiProjectRouteImport.update({
  id: '/api/project',
  path: '/api/project',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentIndexRoute = AppAgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsWorkflowIdRunRunIdRoute =
  AppWorkflowsWorkflowIdRunRunIdRouteImport.update({
    id: '/workflows/$workflowId/run/$runId',
    path: '/workflows/$workflowId/run/$runId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAgentAgentIdRunRunIdRoute = AppAgentAgentIdRunRunIdRouteImport.update({
  id: '/agent/$agentId/run/$runId',
  path: '/agent/$agentId/run/$runId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/api/project': typeof ApiProjectRoute
  '/api/runtime': typeof ApiRuntimeRoute
  '/agent/': typeof AppAgentIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/workflows/': typeof AppWorkflowsIndexRoute
  '/agent/$agentId/run/$runId': typeof AppAgentAgentIdRunRunIdRoute
  '/workflows/$workflowId/run/$runId': typeof AppWorkflowsWorkflowIdRunRunIdRoute
}
export interface FileRoutesByTo {
  '/api/project': typeof ApiProjectRoute
  '/api/runtime': typeof ApiRuntimeRoute
  '/': typeof AppIndexRoute
  '/agent': typeof AppAgentIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/workflows': typeof AppWorkflowsIndexRoute
  '/agent/$agentId/run/$runId': typeof AppAgentAgentIdRunRunIdRoute
  '/workflows/$workflowId/run/$runId': typeof AppWorkflowsWorkflowIdRunRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/api/project': typeof ApiProjectRoute
  '/api/runtime': typeof ApiRuntimeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agent/': typeof AppAgentIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/workflows/': typeof AppWorkflowsIndexRoute
  '/_app/agent/$agentId/run/$runId': typeof AppAgentAgentIdRunRunIdRoute
  '/_app/workflows/$workflowId/run/$runId': typeof AppWorkflowsWorkflowIdRunRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/project'
    | '/api/runtime'
    | '/agent/'
    | '/settings/'
    | '/workflows/'
    | '/agent/$agentId/run/$runId'
    | '/workflows/$workflowId/run/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/project'
    | '/api/runtime'
    | '/'
    | '/agent'
    | '/settings'
    | '/workflows'
    | '/agent/$agentId/run/$runId'
    | '/workflows/$workflowId/run/$runId'
  id:
    | '__root__'
    | '/_app'
    | '/api/project'
    | '/api/runtime'
    | '/_app/'
    | '/_app/agent/'
    | '/_app/settings/'
    | '/_app/workflows/'
    | '/_app/agent/$agentId/run/$runId'
    | '/_app/workflows/$workflowId/run/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiProjectRoute: typeof ApiProjectRoute
  ApiRuntimeRoute: typeof ApiRuntimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/runtime': {
      id: '/api/runtime'
      path: '/api/runtime'
      fullPath: '/api/runtime'
      preLoaderRoute: typeof ApiRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project': {
      id: '/api/project'
      path: '/api/project'
      fullPath: '/api/project'
      preLoaderRoute: typeof ApiProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows/': {
      id: '/_app/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent/': {
      id: '/_app/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AppAgentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/$workflowId/run/$runId': {
      id: '/_app/workflows/$workflowId/run/$runId'
      path: '/workflows/$workflowId/run/$runId'
      fullPath: '/workflows/$workflowId/run/$runId'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdRunRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent/$agentId/run/$runId': {
      id: '/_app/agent/$agentId/run/$runId'
      path: '/agent/$agentId/run/$runId'
      fullPath: '/agent/$agentId/run/$runId'
      preLoaderRoute: typeof AppAgentAgentIdRunRunIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAgentIndexRoute: typeof AppAgentIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
  AppAgentAgentIdRunRunIdRoute: typeof AppAgentAgentIdRunRunIdRoute
  AppWorkflowsWorkflowIdRunRunIdRoute: typeof AppWorkflowsWorkflowIdRunRunIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAgentIndexRoute: AppAgentIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
  AppAgentAgentIdRunRunIdRoute: AppAgentAgentIdRunRunIdRoute,
  AppWorkflowsWorkflowIdRunRunIdRoute: AppWorkflowsWorkflowIdRunRunIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiProjectRoute: ApiProjectRoute,
  ApiRuntimeRoute: ApiRuntimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
